dist: xenial   # required for Python >= 3.7

sudo: false

language: python

services:
  - mongodb
  - mysql
  - postgresql
  - redis-server

cache: pip

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"

before_script:
  - sleep 5
  # Create databases
  - mongo db --eval 'db.createUser({user:"test_user",pwd:"test_password",roles:["readWrite"]});'
  - mysql -e 'CREATE DATABASE py_abac CHARACTER SET utf8 COLLATE utf8_bin;'
  - psql -c "CREATE DATABASE py_abac ENCODING='UTF8';" -U postgres

install:
  - make deps

script:
  # All default tests with in-memory storage
  - make coverage MARK='"not integration"' COVERAGE_OPTS="--cov-append"
  # MongoDB storage integration tests
  - MONGODB_HOST="127.0.0.1:27017" make coverage MARK='"mongo"' COVERAGE_OPTS="--cov-append"
  # MySQL storage integration tests
  - SQL_HOST="mysql+pymysql://root@127.0.0.1/py_abac" make coverage MARK='"sql"' COVERAGE_OPTS="--cov-append"
  # Postgres storage integration tests
  - SQL_HOST="postgresql+psycopg2cffi://postgres:@localhost/py_abac" make coverage MARK='"sql"' COVERAGE_OPTS="--cov-append"
  # Redis storage integration tests
  - REDIS_HOST="127.0.0.1" REDIS_PORT="6379" make coverage MARK='"redis"' COVERAGE_OPTS="--cov-append"

after_success:
  - bash <(curl -s https://codecov.io/bash)
